 CREATE TABLE "FERYEL"."ORDERITEM" 
   (	"ORDERITEMID" NUMBER(4,0) NOT NULL ENABLE, 
	"ORDER_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"PRODUCTID" NUMBER(4,0) NOT NULL ENABLE, 
	"QUANTITY" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "ORDERITEM_PK" PRIMARY KEY ("ORDERITEMID")

CREATE TABLE "FERYEL"."ORDERS" 
   (	"ORDER_ID" NUMBER(4,0) NOT NULL ENABLE, 
	"ORDER_DATE" DATE NOT NULL ENABLE, 
	"STATUS_ORDER" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CUSTOMERID" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ORDER_ID")
